# Generated by Django 4.0.6 on 2022-12-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_id', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('1', 'male'), ('2', 'female ')], max_length=100)),
                ('date_of_birth', models.DateTimeField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('1', 'level 100'), ('2', 'level 200'), ('3', 'level 300'), ('4', 'level 400')], max_length=10)),
                ('admission_number', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=11)),
                ('student_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
